### ISSUE TITLE
Adjust inventory on Ansible Collection

### ISSUE THREAD

**Issue by dyegoe** [dyegoe/tasks#4]
Change ansible inventory var `ANSIBLE_INVENTORY_FILE` to a list
```yaml
ANSIBLE_INVENTORY_FILES:
  live: "inventories/live/aws_ec2.yml"
  local: "example/inventory.yaml"
```

If parameter inventory is provided, check if the file exists, if not, check if the name is one of the keys from the dictionary.
If parameter isn't provided, check of key `default`, otherwise, first item on the dict.
